[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"

[deploy.restartPolicy]
type = "on-failure"
maxRetries = 10

[env]
BITRATE = "128k"
SOURCES_FILE = "sources.txt"
CACHE_DIR = "/app/cache"